Resolve Issue #134
youngeek-0410/fes-order pull request #140
Opened 2021-05-31 14:22 UTC by Dz0526

値段の追加

2021-05-31 15:42 UTC, kathmandu777 reviewed
疑問点をコメントしておいたので確認お願いします。

2021-05-31 15:42 UTC, kathmandu777 commented on app/views/users/new.html.slim
> +    = f.submit '登録', class: 'ui button primary us-w-100 us-h-45-px', style: 'font-weight: 100; margin-top: 20px;'
ここは#135の修正箇所だけど、以前にコミットした部分だから含まれてるのかな？Gitの仕様が良く理解できていないのでわかりません。

2021-05-31 16:18 UTC, Dz0526 commented on app/views/users/new.html.slim
> +    = f.submit '登録', class: 'ui button primary us-w-100 us-h-45-px', style: 'font-weight: 100; margin-top: 20px;'
この場合どうすれば良いいいですかね🤔

2021-05-31 16:24 UTC, Dz0526 commented on app/views/users/new.html.slim
> +    = f.submit '登録', class: 'ui button primary us-w-100 us-h-45-px', style: 'font-weight: 100; margin-top: 20px;'
これは master からブランチを切るべきだった？

2021-05-31 21:44 UTC, Ichigo-dev commented on app/views/users/new.html.slim
> +    = f.submit '登録', class: 'ui button primary us-w-100 us-h-45-px', style: 'font-weight: 100; margin-top: 20px;'
これはだいきがissue/135 からブランチ切ったんじゃない？？
基本的にブランチを切るときは
1. master を最新にする
2. master からブランチをきる

上の流れで、
他ブランチの変更を取り入れたいときは他ブランチをmasterにマージしてから自身のブランチに masterをマージ or リベースする

2021-05-31 21:53 UTC, Ichigo-dev requested changes

2021-05-31 21:53 UTC, Ichigo-dev commented on app/views/shops/show.html.slim
>            .us-mt-5.us-fz-14 = slice20(product.description)
デザイン的にかつかつな感じしてきたからこの行消しちゃって！

2021-05-31 21:53 UTC, Ichigo-dev commented on app/views/products/show.html.slim
> +  h2 = "1個　#{@product.price_tax}円（税込み）"
h2 => h3 でお願いー
あと個人的に "#{@product.price_tax}円（税込み）" だけで良いかなー

2021-05-31 21:58 UTC, Ichigo-dev commented
あと購入ボタンの上に現在の金額を非同期に表示してあげれると良いかな
現在: OO 円（税込）
みたいな感じで個数に応じて変わるイメージ。
非同期にする方法は フォームを丸ごと Angular でコンポーネント化してもいいし、
assets/javascripts/ 下にjsファイル作ってあげてそこでjquery でやってあげても良いです

2021-05-31 21:59 UTC, Ichigo-dev commented
あと ブランチ作ったら Draft にしといて欲しいーー

2021-05-31 22:37 UTC, Dz0526 commented
これ Angular で書く場合、javascript 配下で form 的なディレクトリ作って書くイメージですかね

2021-06-01 00:47 UTC, Ichigo-dev commented
そうだね、ただ正直目的に対してやることが多すぎるからjquery で良いかなー
いつかangular => react するかもしれないし

2021-06-03 07:22 UTC, Ichigo-dev commented on app/views/shops/show.html.slim
>            .us-mt-5.us-fz-14 = slice20(product.description)
ごめんこれ超わかりにくかったかもだけど
description消して欲しい！
priceは載せといて！

2021-06-03 07:25 UTC, Ichigo-dev requested changes
レビュー以外で
税込み => 税込
に文言を変更して欲しいです。

2021-06-03 07:25 UTC, Ichigo-dev commented on app/assets/javascripts/product_show.js.erb
> +  message.innerText = "現在: " + total_price + "（税込み）"
単位がないから
￥ 150
みたいにしてほしい！

2021-06-03 07:25 UTC, Ichigo-dev commented on app/views/products/show.html.slim
> +  h3 = "#{@product.price_tax}円（税込み）"
単位を全体で
￥に統一したい！

2021-06-03 07:25 UTC, Ichigo-dev commented on app/views/products/show.html.slim
> +    = javascript_include_tag "product_show", "data-turbolinks-track" => "reload"
jsのscriptタグはファイル末尾に持ってきて欲しい！

2021-06-03 07:29 UTC, Ichigo-dev commented on app/views/products/show.html.slim
> +    h4#total_price = "現在:#{@product.price_tax}円（税込み）"
スタイル的な話で
h4 => p.us-fz-18
に変更して欲しい！

2021-06-03 12:04 UTC, Ichigo-dev commented
良い感じ！
追加での要望なんだけど、購入時の `現在： ￥OO `のところで個数だけじゃなくて使用クーポンにも応じて料金が変わるようにしてほしい！

2021-06-04 04:56 UTC, Dz0526 commented
クーポンってユーザに使うかどうか聞きますか？勝手に反映しちゃってもいいのか
あと今は買い物が出来なくてクーポン取得できない感じなんですけど、どうやって動作確認するべきですか

2021-06-04 04:59 UTC, Ichigo-dev commented
@Dz0526 
購入画面でクーポンを指定するセレクトボックスがあるから、また個数の時と同じようにクーポン選択に応じて変えて欲しい！
クーポンの取得の流れは
商品購入 => クイズプレイ => クーポン獲得(使える店はランダム)
モックデータはないから上をやってほしいー

2021-06-04 05:03 UTC, Dz0526 commented
カード登録の所でpayjp関連のマンズと同じエラー出てます…
そっちのエラーから着手した方がいいですかね

2021-06-04 06:44 UTC, Ichigo-dev commented
@Dz0526 
エラー治ってるから masterブランチ リベースして取り込んで開発進めてほしい！

2021-06-10 01:44 UTC, Ichigo-dev requested changes

2021-06-10 01:44 UTC, Ichigo-dev commented on app/views/products/show.html.slim
> +      = f.collection_select :coupon_id, @coupons, :discount, :name, include_blank: '使用しない'
receipts_controller#create でcoupon_idを使ってるからこれだとバグっちゃう気がするな

2021-06-10 01:45 UTC, Ichigo-dev commented on app/views/products/show.html.slim
> +      = f.collection_select :coupon_id, @coupons, :discount, :name, include_blank: '使用しない'
購入後に`rails c`とかでreceiptsのレコード見てクーポンがちゃんと紐づいてたらOKって感じだね

2021-06-11 12:47 UTC, Ichigo-dev approved these changes

2021-06-11 12:47 UTC, Ichigo-dev approved these changes

2021-06-11 12:48 UTC, merged