Resolve Issue #143
youngeek-0410/fes-order pull request #146
Opened 2021-06-02 07:38 UTC by kathmandu777

デザインは正直言ってひどいです。
画像の更新処理がこの実装方法でいいのか不明です。

2021-06-02 07:52 UTC, Dz0526 approved these changes
多分おうけい

2021-06-03 07:41 UTC, Ichigo-dev requested changes
デザイン結構良い感じよ

2021-06-03 07:41 UTC, Ichigo-dev commented on app/views/management/shops/show.html.slim
> +        td =current_shop.updated_at
左側の項目名は th にして欲しい！

2021-06-03 07:41 UTC, Ichigo-dev commented on app/views/management/shops/show.html.slim
> +        td =current_shop.email
= の後に 半角スペース入れて欲しいー

2021-06-03 07:41 UTC, Ichigo-dev commented on app/views/management/shops/show.html.slim
> +    = image_tag @shop.image
これtableの下に移動させてー

2021-06-03 07:41 UTC, Ichigo-dev commented on app/views/management/shops/show.html.slim
> +
```
  .us-mt-15
    = link_to '編集', edit_management_shop_path, class: 'ui button grey us-fw-400', style: 'font-weight: 100'
```
みたいに変更して欲しい
&
28行目消して欲しい！

2021-06-03 07:41 UTC, Ichigo-dev commented on app/views/management/shops/show.html.slim
> +  .us-card
これ多分消して良いはず？

2021-06-03 07:41 UTC, Ichigo-dev commented on app/views/management/shops/edit.html.slim
> +  = form_with url: management_shop_path,model: @shop, class: 'ui form', id: 'shop_form', local: true do |f|
, の後にスペース入れて欲しい！

2021-06-03 07:41 UTC, Ichigo-dev commented on app/controllers/management/shops_controller.rb
> +
userモデルで create, updateで 関数を分けてなくてもできる実装がされているからそれ見て変更して欲しい！

2021-06-03 07:42 UTC, Ichigo-dev commented
見た目部分しか見れてないからまた見ます

2021-06-03 08:13 UTC, Ichigo-dev commented on app/views/management/shops/show.html.slim
> +  .us-card
11行目のことねー

2021-06-03 08:13 UTC, Ichigo-dev commented on app/controllers/management/shops_controller.rb
> +
allow_nil

2021-06-04 01:33 UTC, kathmandu777 commented
userモデルで create, updateで 関数を分けてなくてもできる実装がされているからそれ見て変更して欲しい！
=> これができてるかがわからない

画像に対する検証は行いますか？（大きさとかファイル容量とか）

2021-06-04 03:51 UTC, kathmandu777 commented
画像に対する検証は行いますか？（大きさとかファイル容量とか）

2021-06-04 03:54 UTC, kathmandu777 commented
```ruby
flash[:success] = 'ショップ情報を更新しました。'
flash[:error] = 'ショップ情報の更新に失敗しました。'
```
サクセス＆エラーメッセージを表示するように実装しましたが、management/application.html.slimにflashを表示する関数がないので表示されません。このブランチで修正していいですか？

2021-06-04 04:37 UTC, Ichigo-dev commented
> userモデルで create, updateで 関数を分けてなくてもできる実装がされているからそれ見て変更して欲しい！
> => 一応実装してみましたが、これであってるかがわかりません。

https://github.com/youngeek-0410/fes-order/blob/master/app/models/user.rb#L14
ここがその部分ー
allow_nil っていうのが必要になるね

2021-06-04 04:38 UTC, Ichigo-dev commented
> 画像に対する検証は行いますか？（大きさとかファイル容量とか）

1MBで制限かけて欲しい！

2021-06-04 04:38 UTC, Ichigo-dev commented
> サクセス＆エラーメッセージを表示するように実装しましたが、management/application.html.slimにflashを表示する関数がないので表示されません。このブランチで修正していいですか？

お願い！

2021-06-04 04:42 UTC, Ichigo-dev commented on app/views/management/shops/show.html.slim
> +.ui.container
多分 .ui.container で包んであげなくても table と同じインデントにしてあげれば良いと思う

2021-06-04 07:23 UTC, Ichigo-dev commented
良い感じ！

追加での要望なんだけど、
imageのバリデーションでファイル形式を
jpg, jpeg, png に制限してほしい！

それと画像表示を良い感じにするために
application.scss に
`
.us-w-500 {
  width: 500px;
}
`
を追加してあげて、それを管理画面のimgタグに指定してほしい！
（画像サイズのバリデーションは行わない)

2021-06-04 07:26 UTC, Ichigo-dev requested changes

2021-06-04 07:26 UTC, Ichigo-dev commented on app/models/shop.rb
> +  end
https://blog.piyo.tech/posts/2018-06-06-rails-file-validators/
この記事とかのやり方で`validates`とかを使ってあげた方が良いかな

2021-06-04 12:02 UTC, Ichigo-dev commented on app/models/shop.rb
> +  end
https://rubygems.org/gems/file_validators/versions/2.0.2

2021-06-04 12:10 UTC, Ichigo-dev commented on app/models/shop.rb
> +  end
https://github.com/carrierwaveuploader/carrierwave#making-uploads-work-across-form-redisplays

2021-07-15 01:00 UTC, Ichigo-dev commented
引き取った

2021-07-15 01:00 UTC, Ichigo-dev approved these changes

2021-07-15 01:01 UTC, merged