店の商品情報
youngeek-0410/fes-order pull request #166
Opened 2021-07-14 14:34 UTC by Dz0526

2021-07-15 00:55 UTC, Ichigo-dev requested changes
productモデルに 数字の時のバリデーションお願いします!
あと一覧表示でも画像が見れるようにお願いしたいーー
一番左にカラム追加してあげて表示する感じかな

2021-07-15 00:55 UTC, Ichigo-dev commented on app/controllers/management/products_controller.rb
> +      render 'new'
```
render :new 
```
がいいな

2021-07-15 00:55 UTC, Ichigo-dev commented on app/controllers/management/products_controller.rb
> +    if @product.update(product_params) && @product.update(price_tax: params[:product][:price].to_i * 1.1)
product_params に price_taxの値をmergeしたものを updateの中に入れたいー

2021-07-15 00:55 UTC, Ichigo-dev commented on app/controllers/management/products_controller.rb
> +    @product.destroy
`destroy!`にして失敗時に例外が起こるようにしてほしい、
そして
```
def destroy
    flash[:success] = '商品情報を削除しました'
    @product.destroy!
    redirect_to management_products_path
rescue
　flash[:error] = '商品の削除に失敗しました
    redirect_to management_products_path
end
```
みたいな感じで例外処理書いておいて欲しい

2021-07-15 00:55 UTC, Ichigo-dev commented on app/views/management/products/index.html.slim
> +                = link_to '詳細', management_product_path(product.id), method: :get
編集、削除のリンクに 注文一覧の完成ボタンみたいな感じ、ユーザ画面とかも、でスタイルをつけてほしいーー

2021-07-15 01:02 UTC, Ichigo-dev commented
masterが新しいからリベースお願いー

2021-07-16 11:37 UTC, Ichigo-dev requested changes

2021-07-16 11:37 UTC, Ichigo-dev commented on app/controllers/management/products_controller.rb
> +    flash[:error]
単純にミス

2021-07-16 11:37 UTC, Ichigo-dev commented on app/models/product.rb
> +  validates :price_tax, presence: true, numericality: { only_integer: true }
待ち時間もお願いー

2021-07-16 11:37 UTC, Ichigo-dev commented on app/views/management/products/index.html.slim
> +                = image_tag product.image, class: 'us-w-100px'
デフォルト画像を設定する

2021-07-16 11:37 UTC, Ichigo-dev commented on app/views/management/products/index.html.slim
> +                = link_to '詳細', management_product_path(product.id), method: :get, class: 'ui button grey us-fw-400', style: 'font-weight: 100'
編集ボタン
編集　=> グレイ
詳細　=> 青

2021-07-17 13:10 UTC, Ichigo-dev requested changes

2021-07-17 13:10 UTC, Ichigo-dev commented on app/controllers/management/products_controller.rb
> +      flash[:else] = '商品情報の更新に失敗しました'
else???

2021-07-17 13:16 UTC, Ichigo-dev commented
あと追加でお願いしたいんだけど、
編集・詳細ページに戻るボタンを置きたいな、
あと商品追加ボタンが商品一覧の下だと見にくいから上がいいな

2021-07-17 13:17 UTC, Dz0526 commented on app/controllers/management/products_controller.rb
> +      flash[:else] = '商品情報の更新に失敗しました'
間違えましたwww

2021-07-31 13:35 UTC, Ichigo-dev reviewed
大変遅れやした、
あとちょいで良さそう

2021-07-31 13:35 UTC, Ichigo-dev commented on app/controllers/management/products_controller.rb
> +      flash[:error] = '商品情報の更新に失敗しました'
今気づいたけど
`商品情報の追加に失敗しました`だね

2021-07-31 13:35 UTC, Ichigo-dev commented on app/views/layouts/management/application.html.slim
> +        i.angle.left.icon.huge
ごめんよ、、そういうことじゃないんだ、、
編集、削除、詳細とかのリンクとおんなじイメージ
もしイメージ湧かなかったら今度のMTGで話そうかな

2021-08-05 12:57 UTC, Dz0526 commented on app/views/layouts/management/application.html.slim
> +        i.angle.left.icon.huge
あーなるほど。
編集は詳細に戻って、詳細はルートに戻るって感じですかね。
位置は下の方でいいですか？

2021-08-14 15:23 UTC, Ichigo-dev approved these changes

2021-08-14 15:23 UTC, Ichigo-dev commented
マージしまーす
ありがとうー

2021-08-14 15:23 UTC, merged